version: '3.1'

services:
  crust-db:
    image: percona:8.0
    networks:
      - crust
    env_file:
      - config.crust-db.env
    volumes:
      - ./data/crust-db:/var/lib/mysql
    restart: on-failure

  crust-api-system:
    image: crusttech/api-system:${CRUST_VERSION}
    depends_on:
      - crust-db
      - didmos-satosa
    networks:
      - party
      - crust
    env_file:
      - config.crust-api.env
      - config.crust-api-system.env
    environment:
      VIRTUAL_HOST:            system.api.${DOMAIN}
      LETSENCRYPT_HOST:        system.api.${DOMAIN}
      AUTH_JWT_COOKIE_DOMAIN:  .api.${DOMAIN}
      AUTH_OIDC_ISSUER:        https://satosa.didmos.${DOMAIN}
      AUTH_OIDC_REDIRECT_URL:  https://system.api.${DOMAIN}/oidc/callback
      AUTH_OIDC_APP_URL:       https://${DOMAIN}/
      AUTH_OIDC_COOKIE_DOMAIN: .${DOMAIN}
    volumes:
      - ./data/crust-api-system/store:/crust/var/store
    restart: on-failure

  crust-api-crm:
    image: crusttech/api-crm:${CRUST_VERSION}
    depends_on:
      - crust-db
    networks:
      - party
      - crust
    env_file:
      - config.crust-api.env
      - config.crust-api-crm.env
      - config.crust-api-system.env
    environment:
      VIRTUAL_HOST:     crm.api.${DOMAIN}
      LETSENCRYPT_HOST: crm.api.${DOMAIN}
      AUTH_JWT_COOKIE_DOMAIN:  .api.${DOMAIN}
      AUTH_OIDC_ISSUER:        https://satosa.didmos.${DOMAIN}
      AUTH_OIDC_REDIRECT_URL:  https://system.api.${DOMAIN}/oidc/callback
      AUTH_OIDC_APP_URL:       https://${DOMAIN}/
      AUTH_OIDC_COOKIE_DOMAIN: .${DOMAIN}
    volumes:
      - ./data/crust-api-crm/store:/crust/var/store
    restart: on-failure

  crust-api-messaging:
    image: crusttech/api-messaging:${CRUST_VERSION}
    depends_on:
      - crust-db
    networks:
      - party
      - crust
    env_file:
      - config.crust-api.env
      - config.crust-api-messaging.env
      - config.crust-api-system.env
    environment:
      VIRTUAL_HOST:     messaging.api.${DOMAIN}
      LETSENCRYPT_HOST: messaging.api.${DOMAIN}
      AUTH_JWT_COOKIE_DOMAIN:  .api.${DOMAIN}
      AUTH_OIDC_ISSUER:        https://satosa.didmos.${DOMAIN}
      AUTH_OIDC_REDIRECT_URL:  https://system.api.${DOMAIN}/oidc/callback
      AUTH_OIDC_APP_URL:       https://${DOMAIN}/
      AUTH_OIDC_COOKIE_DOMAIN: .${DOMAIN}
    volumes:
      - ./data/crust-api-messaging/store:/crust/var/store
    restart: on-failure

  crust-webapp:
    image: crusttech/webapp:${CRUST_VERSION}
    networks:
      - party
    environment:
      VIRTUAL_HOST:     ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
    depends_on:
      - crust-api-crm
      - crust-api-messaging
      - crust-api-system
      - didmos-frontend
      - didmos-satosa
    volumes:
      - ./config.crust-webapp.js:/crust/webapp/config.js:ro
      - ./config.crust-webapp.js:/crust/webapp/crm/config.js:ro
      - ./config.crust-webapp.js:/crust/webapp/messaging/config.js:ro
      - ./config.crust-webapp.js:/crust/webapp/admin/config.js:ro
    restart: on-failure

  didmos-mongo:
    image: crusttech/didmos2-mongodb:${DIDMOS_VERSION}
    restart: always
    networks:
      - didmos
    env_file:
      - config.didmos-mongo.env
    environment:
      SATOSA_FRONTEND: https://frontend.didmos.${DOMAIN}
    volumes:
      - ./data/didmos-mongo:/data/db

  didmos-satosa:
    image: crusttech/didmos2-satosa:${DIDMOS_VERSION}
    depends_on:
      - didmos-mongo
      - didmos
    networks:
      - party
      - didmos
    env_file:
      - config.didmos-satosa.env
    environment:
      VIRTUAL_HOST:            satosa.didmos.${DOMAIN}
      LETSENCRYPT_HOST:        satosa.didmos.${DOMAIN}
      SATOSA_BASE_HOST:        satosa.didmos.${DOMAIN}
      SATOSA_REGISTRATION_URL: https://frontend.didmos.${DOMAIN}
    volumes:
      - ./data/didmos-satosa/credentials:/etc/satosa/credentials

  didmos-ldap:
    image: crusttech/didmos2-openldap:${DIDMOS_VERSION}
    networks:
      - didmos
    depends_on:
      - didmos-mongo
    env_file:
      - config.didmos-ldap.env
    volumes:
      - ./data/didmos-ldap:/var/lib/ldap

  didmos:
    image: crusttech/didmos2-didmos:${DIDMOS_VERSION}
    depends_on:
      - didmos-ldap
    networks:
      - party
      - didmos
    env_file:
      - config.didmos.env
    environment:
      - VIRTUAL_HOST=didmos.${DOMAIN}
      - LETSENCRYPT_HOST=didmos.${DOMAIN}
      - LUI_OIDC_AUTH_SERVER=https://satosa.didmos.${DOMAIN}/OIDC/
      # Be careful with dicts/lists as they handle quotes differently
      - SELF_REG_VALIDATION_ENDPOINT='https://frontend.didmos.${DOMAIN}/setpassword'
      - SELF_REG_MAIL_BODY_CRUSTURL='https://${DOMAIN}'


  didmos-frontend:
    image: crusttech/didmos2-frontend:${DIDMOS_VERSION}
    networks:
      - party
      - didmos
    env_file:
      - config.didmos-frontend.env
    environment:
      VIRTUAL_HOST:       frontend.didmos.${DOMAIN}
      LETSENCRYPT_HOST:   frontend.didmos.${DOMAIN}
      OIDC_FE_ISSUER:     https://satosa.didmos.${DOMAIN}
      FE_URL:              https://frontend.didmos.${DOMAIN}
      BE_URL:              https://didmos.${DOMAIN}
      SETPASSWORD_GOBACK: https://${DOMAIN}
      EXITLINK_HREF:      https://${DOMAIN}

networks:
  crust:
  didmos:
  party:
    external: true
