version: '2'

services:
  db1:
    image: percona:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=crust
      - MYSQL_DATABASE=crust
      - MYSQL_USER=crust
      - MYSQL_PASSWORD=crust
    volumes:
    - $PWD/data/db:/var/lib/mysql
    - ./mysql-init-definer.sql:/docker-entrypoint-initdb.d/mysql-init-definer.sql
    restart: on-failure

  sam:
    image: crusttech/api-sam
    depends_on:
      - db1
      - system
    env_file:
      - $PWD/crust.env
      - $PWD/crust-sam.env
    restart: on-failure

  crm:
    image: crusttech/api-crm
    depends_on:
      - db1
      - system
    env_file:
      - $PWD/crust.env
      - $PWD/crust-crm.env
    restart: on-failure

  system:
    image: crusttech/api-system
    depends_on:
      - db1
    env_file:
      - $PWD/crust.env
      - $PWD/crust-system.env
    restart: on-failure
