version: '2'

services:
  crust-system:
    image: crusttech/api-system
    networks:
      - party
    env_file:
      - ./system.env
      - ../crust.env
    restart: on-failure

networks:
  party:
    external: true
